### ISSUE TITLE
Amount and price calculation are wrong

### ISSUE THREAD

**Issue by ingebyd** [bitcoin-atom/atom-engine#1]
reproduce behavior
go to Trade tab and place the order (tested with 0.01 btc / 100 bca)
order will appeares in active orders with wrong calculated amounts
https://yadi.sk/i/TOwJQiG1FT7ldQ

windows 10 x64

**Comment by rootSig** [comment]
@vladislavRzhevicky thanks, we have reproduced the error. To be fixed in the coming release.

**Comment by rootSig** [comment]
@vladislavRzhevicky fixed [in the latest release](https://github.com/bitcoin-atom/atom-engine/releases/latest).
