### ISSUE TITLE
Substring the values

### ISSUE THREAD

**Issue by ingebyd** [bitcoin-atom/atom-engine#2]
allow max amount of numbers in the string
https://yadi.sk/i/EfujJrLfCL99Ug

**Comment by rootSig** [comment]
thanks for reporting @vladislavRzhevicky, will limit the decimal places to 8 (satoshis) in Bitcoin-like currencies

**Comment by rootSig** [comment]
@vladislavRzhevicky limit applied on the server-side [in the latest release](https://github.com/bitcoin-atom/atom-engine/releases/latest).

Planned to limit the decimals count on the client side in the next release.

**Comment by vladislavRzhevicky** [comment]
@rootSig https://yadi.sk/i/qvs7aaHkei8ifA

**Comment by ingebyd** [comment]
@rootSig also, i can put more that 21mil for btc and bca. Not critical, but will be nice from UI-side have this kind of limits as well
