### ISSUE TITLE
disconnected from server after idle several minutes

### ISSUE THREAD

**Issue by yellowtns** [bitcoin-atom/atom-engine#3]
i don't know if this a normal? sometime BCA Node and Engine disconnected from server, when I try to refresh wallet, it gets stuck in the process, here is a full log. thank you

[https://pastebin.com/BPc2aiuB](https://pastebin.com/BPc2aiuB)
-or-
[https://gist.github.com/4db2fbe3fac6c8dee3b4cc29ec06cb99](https://gist.github.com/zalfadisha/4db2fbe3fac6c8dee3b4cc29ec06cb99)
`

**Comment by rootSig** [comment]
Thanks a lot @yellowtns for reporting.

I believe this has been addressed [in the latest Tritium release](https://github.com/bitcoin-atom/atom-engine/releases/latest).
