### ISSUE TITLE
swap process waiting period

### ISSUE THREAD

**Issue by POpi1** [bitcoin-atom/atom-engine#4]
how long do I wait FOR Chains to swap If I take order from markets

**Comment by rootSig** [comment]
hey @POpi1, it's normally within 1 minute, except for "stuck" orders, meaning orders submitted by clients which had permanently gone offline. To address this, we've rolled out a new feature which enforces only orders from online users to be shown in the Markets page.

Please update your client to [the latest Tritium release](https://github.com/bitcoin-atom/atom-engine/releases/latest).
